// Comprehensive mock data for unified analytics

import { ClassAnalytics, OverviewStats, AtRiskAlert } from './analyticsTypes';

export const mockClassesAnalytics: ClassAnalytics[] = [
  {
    classId: 'calc2',
    className: 'Calculus II',
    courseCode: 'MATH 251',
    color: '#f59e0b', // amber
    currentGrade: 87,
    letterGrade: 'B+',
    trend: 'up',
    trendValue: 3.5,
    stats: {
      assignmentsCompleted: 14,
      totalAssignments: 16,
      averageScore: 85.3,
      rank: 12,
    },
    gradeBreakdown: [
      {
        name: 'Exams',
        weight: 40,
        currentScore: 84,
        maxPoints: 300,
        earnedPoints: 252,
        impact: 'neutral',
        itemCount: 3,
      },
      {
        name: 'Homework',
        weight: 30,
        currentScore: 92,
        maxPoints: 500,
        earnedPoints: 460,
        impact: 'positive',
        itemCount: 10,
      },
      {
        name: 'Quizzes',
        weight: 20,
        currentScore: 88,
        maxPoints: 200,
        earnedPoints: 176,
        impact: 'positive',
        itemCount: 4,
      },
      {
        name: 'Participation',
        weight: 10,
        currentScore: 95,
        maxPoints: 100,
        earnedPoints: 95,
        impact: 'positive',
        itemCount: 1,
      },
    ],
    conceptMastery: [
      { id: '1', name: 'Derivatives', status: 'strong', score: 94, lastAssessed: '2024-11-08' },
      { id: '2', name: 'Integration', status: 'strong', score: 89, lastAssessed: '2024-11-10' },
      { id: '3', name: 'Series & Sequences', status: 'needs-work', score: 72, lastAssessed: '2024-11-09' },
      { id: '4', name: 'Applications', status: 'needs-work', score: 68, lastAssessed: '2024-11-05' },
      { id: '5', name: 'Differential Equations', status: 'not-assessed' },
    ],
    moodData: {
      currentMood: 'Confident',
      currentMoodScore: 4,
      difficulty: 4,
      confidence: 4,
      moodTrend: [
        { date: '2024-11-05', mood: 'Stressed', score: 2, hasEvent: true, eventType: 'test' },
        { date: '2024-11-06', mood: 'Neutral', score: 3 },
        { date: '2024-11-07', mood: 'Hopeful', score: 4 },
        { date: '2024-11-08', mood: 'Confident', score: 4, hasEvent: true, eventType: 'quiz' },
        { date: '2024-11-09', mood: 'Neutral', score: 3 },
        { date: '2024-11-10', mood: 'Happy', score: 5, hasEvent: true, eventType: 'assignment' },
        { date: '2024-11-11', mood: 'Confident', score: 4 },
      ],
    },
    recentActivity: [
      {
        id: '1',
        type: 'quiz',
        title: 'Integration Quiz',
        date: '2024-11-08',
        score: 92,
        maxScore: 100,
        mood: 'Confident',
        trend: 'improved',
      },
      {
        id: '2',
        type: 'assignment',
        title: 'Homework 10',
        date: '2024-11-10',
        score: 95,
        maxScore: 100,
        mood: 'Happy',
      },
      {
        id: '3',
        type: 'test',
        title: 'Midterm Exam',
        date: '2024-11-05',
        score: 78,
        maxScore: 100,
        mood: 'Stressed',
        trend: 'declined',
      },
    ],
  },
  {
    classId: 'bio101',
    className: 'Biology 101',
    courseCode: 'BIO 101',
    color: '#ef4444', // red
    currentGrade: 76,
    letterGrade: 'C',
    trend: 'down',
    trendValue: -4.2,
    stats: {
      assignmentsCompleted: 10,
      totalAssignments: 14,
      averageScore: 74.8,
    },
    gradeBreakdown: [
      {
        name: 'Exams',
        weight: 50,
        currentScore: 72,
        maxPoints: 400,
        earnedPoints: 288,
        impact: 'negative',
        itemCount: 4,
      },
      {
        name: 'Lab Reports',
        weight: 30,
        currentScore: 82,
        maxPoints: 300,
        earnedPoints: 246,
        impact: 'positive',
        itemCount: 6,
      },
      {
        name: 'Quizzes',
        weight: 15,
        currentScore: 78,
        maxPoints: 150,
        earnedPoints: 117,
        impact: 'neutral',
        itemCount: 3,
      },
      {
        name: 'Participation',
        weight: 5,
        currentScore: 85,
        maxPoints: 50,
        earnedPoints: 42.5,
        impact: 'positive',
        itemCount: 1,
      },
    ],
    conceptMastery: [
      { id: '1', name: 'Cell Structure', status: 'strong', score: 88, lastAssessed: '2024-11-02' },
      { id: '2', name: 'DNA & RNA', status: 'needs-work', score: 65, lastAssessed: '2024-11-07' },
      { id: '3', name: 'Cellular Respiration', status: 'needs-work', score: 70, lastAssessed: '2024-11-06' },
      { id: '4', name: 'Photosynthesis', status: 'needs-work', score: 68, lastAssessed: '2024-11-08' },
      { id: '5', name: 'Genetics', status: 'not-assessed' },
      { id: '6', name: 'Evolution', status: 'not-assessed' },
    ],
    moodData: {
      currentMood: 'Worried',
      currentMoodScore: 2,
      difficulty: 5,
      confidence: 2,
      moodTrend: [
        { date: '2024-11-05', mood: 'Frustrated', score: 2 },
        { date: '2024-11-06', mood: 'Stressed', score: 2, hasEvent: true, eventType: 'test' },
        { date: '2024-11-07', mood: 'Disappointed', score: 1, hasEvent: true, eventType: 'quiz' },
        { date: '2024-11-08', mood: 'Neutral', score: 3 },
        { date: '2024-11-09', mood: 'Worried', score: 2 },
        { date: '2024-11-10', mood: 'Hopeful', score: 3, hasEvent: true, eventType: 'assignment' },
        { date: '2024-11-11', mood: 'Worried', score: 2 },
      ],
    },
    recentActivity: [
      {
        id: '1',
        type: 'quiz',
        title: 'DNA Structure Quiz',
        date: '2024-11-07',
        score: 65,
        maxScore: 100,
        mood: 'Disappointed',
        trend: 'declined',
      },
      {
        id: '2',
        type: 'assignment',
        title: 'Lab Report 5',
        date: '2024-11-10',
        score: 85,
        maxScore: 100,
        mood: 'Hopeful',
        trend: 'improved',
      },
      {
        id: '3',
        type: 'test',
        title: 'Chapter 5-6 Exam',
        date: '2024-11-06',
        score: 68,
        maxScore: 100,
        mood: 'Stressed',
      },
    ],
  },
  {
    classId: 'eng201',
    className: 'English Literature',
    courseCode: 'ENG 201',
    color: '#a855f7', // purple
    currentGrade: 94,
    letterGrade: 'A',
    trend: 'stable',
    trendValue: 0.5,
    stats: {
      assignmentsCompleted: 12,
      totalAssignments: 12,
      averageScore: 92.5,
      rank: 3,
    },
    gradeBreakdown: [
      {
        name: 'Essays',
        weight: 50,
        currentScore: 95,
        maxPoints: 500,
        earnedPoints: 475,
        impact: 'positive',
        itemCount: 5,
      },
      {
        name: 'Discussions',
        weight: 25,
        currentScore: 92,
        maxPoints: 250,
        earnedPoints: 230,
        impact: 'positive',
        itemCount: 10,
      },
      {
        name: 'Presentations',
        weight: 15,
        currentScore: 96,
        maxPoints: 150,
        earnedPoints: 144,
        impact: 'positive',
        itemCount: 2,
      },
      {
        name: 'Participation',
        weight: 10,
        currentScore: 90,
        maxPoints: 100,
        earnedPoints: 90,
        impact: 'positive',
        itemCount: 1,
      },
    ],
    conceptMastery: [
      { id: '1', name: 'Literary Analysis', status: 'strong', score: 96, lastAssessed: '2024-11-09' },
      { id: '2', name: 'Character Development', status: 'strong', score: 94, lastAssessed: '2024-11-08' },
      { id: '3', name: 'Themes & Symbolism', status: 'strong', score: 93, lastAssessed: '2024-11-10' },
      { id: '4', name: 'Historical Context', status: 'needs-work', score: 78, lastAssessed: '2024-11-05' },
      { id: '5', name: 'Poetry Analysis', status: 'not-assessed' },
    ],
    moodData: {
      currentMood: 'Happy',
      currentMoodScore: 5,
      difficulty: 2,
      confidence: 5,
      moodTrend: [
        { date: '2024-11-05', mood: 'Happy', score: 5 },
        { date: '2024-11-06', mood: 'Confident', score: 4 },
        { date: '2024-11-07', mood: 'Happy', score: 5 },
        { date: '2024-11-08', mood: 'Excited', score: 5, hasEvent: true, eventType: 'assignment' },
        { date: '2024-11-09', mood: 'Happy', score: 5, hasEvent: true, eventType: 'assignment' },
        { date: '2024-11-10', mood: 'Confident', score: 4 },
        { date: '2024-11-11', mood: 'Happy', score: 5 },
      ],
    },
    recentActivity: [
      {
        id: '1',
        type: 'assignment',
        title: 'Essay: Shakespeare Analysis',
        date: '2024-11-09',
        score: 98,
        maxScore: 100,
        mood: 'Happy',
        trend: 'maintained',
      },
      {
        id: '2',
        type: 'assignment',
        title: 'Character Study',
        date: '2024-11-08',
        score: 94,
        maxScore: 100,
        mood: 'Excited',
      },
      {
        id: '3',
        type: 'assignment',
        title: 'Historical Context Paper',
        date: '2024-11-05',
        score: 82,
        maxScore: 100,
        mood: 'Happy',
        trend: 'declined',
      },
    ],
  },
  {
    classId: 'chem102',
    className: 'Chemistry 102',
    courseCode: 'CHEM 102',
    color: '#10b981', // green
    currentGrade: 85,
    letterGrade: 'B',
    trend: 'stable',
    trendValue: 1.0,
    stats: {
      assignmentsCompleted: 13,
      totalAssignments: 15,
      averageScore: 84.2,
    },
    gradeBreakdown: [
      {
        name: 'Exams',
        weight: 45,
        currentScore: 82,
        maxPoints: 450,
        earnedPoints: 369,
        impact: 'neutral',
        itemCount: 3,
      },
      {
        name: 'Lab Work',
        weight: 35,
        currentScore: 89,
        maxPoints: 350,
        earnedPoints: 311.5,
        impact: 'positive',
        itemCount: 7,
      },
      {
        name: 'Problem Sets',
        weight: 15,
        currentScore: 86,
        maxPoints: 150,
        earnedPoints: 129,
        impact: 'positive',
        itemCount: 5,
      },
      {
        name: 'Participation',
        weight: 5,
        currentScore: 92,
        maxPoints: 50,
        earnedPoints: 46,
        impact: 'positive',
        itemCount: 1,
      },
    ],
    conceptMastery: [
      { id: '1', name: 'Chemical Bonding', status: 'strong', score: 90, lastAssessed: '2024-11-03' },
      { id: '2', name: 'Stoichiometry', status: 'strong', score: 87, lastAssessed: '2024-11-07' },
      { id: '3', name: 'Thermodynamics', status: 'needs-work', score: 75, lastAssessed: '2024-11-09' },
      { id: '4', name: 'Equilibrium', status: 'not-assessed' },
      { id: '5', name: 'Acids & Bases', status: 'not-assessed' },
    ],
    moodData: {
      currentMood: 'Neutral',
      currentMoodScore: 3,
      difficulty: 3,
      confidence: 3,
      moodTrend: [
        { date: '2024-11-05', mood: 'Neutral', score: 3 },
        { date: '2024-11-06', mood: 'Focused', score: 4 },
        { date: '2024-11-07', mood: 'Confident', score: 4, hasEvent: true, eventType: 'quiz' },
        { date: '2024-11-08', mood: 'Neutral', score: 3 },
        { date: '2024-11-09', mood: 'Stressed', score: 2, hasEvent: true, eventType: 'test' },
        { date: '2024-11-10', mood: 'Hopeful', score: 3 },
        { date: '2024-11-11', mood: 'Neutral', score: 3 },
      ],
    },
    recentActivity: [
      {
        id: '1',
        type: 'test',
        title: 'Thermodynamics Exam',
        date: '2024-11-09',
        score: 78,
        maxScore: 100,
        mood: 'Stressed',
        trend: 'declined',
      },
      {
        id: '2',
        type: 'quiz',
        title: 'Stoichiometry Quiz',
        date: '2024-11-07',
        score: 91,
        maxScore: 100,
        mood: 'Confident',
        trend: 'improved',
      },
      {
        id: '3',
        type: 'assignment',
        title: 'Lab Report 6',
        date: '2024-11-06',
        score: 88,
        maxScore: 100,
        mood: 'Focused',
      },
    ],
  },
];

export const mockOverviewStats: OverviewStats = {
  overallGPA: 3.5,
  gpaLetter: 'B+',
  gpaTrend: 'up',
  gpaTrendValue: 0.1,
  completionRate: 87,
  currentWorkload: 325, // points due this week
  overallMoodScore: 3.5,
  totalClasses: 4,
  atRiskClasses: ['bio101'], // Biology 101
};

export const mockAtRiskAlerts: AtRiskAlert[] = [
  {
    classId: 'bio101',
    className: 'Biology 101',
    color: '#ef4444',
    reason: 'multiple-factors',
    currentGrade: 76,
    details: 'Grade dropped 4.2 points. Low mood and confidence. Missing 4 assignments.',
    severity: 'high',
  },
];

