/**
 * Mock Feedback Data
 *
 * Provides realistic mock data for the Feedback Hub when VITE_USE_ACADEMICS_FEEDBACK=true
 * This allows testing without real Canvas/Supabase data.
 */

import type {
  InstructorFeedback,
  FeedbackPattern,
  ImprovementGoal,
  SentimentStats,
  TimelineEntry,
  FeedbackTrend,
} from './feedbackAggregator';

// =====================================================
// MOCK INSTRUCTOR FEEDBACK
// =====================================================

export const mockInstructorFeedback: InstructorFeedback[] = [
  {
    id: 'feedback-1',
    userId: 'mock-user-1',
    submissionId: 'submission-1',
    courseId: 'course-1',
    courseName: 'Introduction to Computer Science',
    assignmentId: 'assignment-1',
    assignmentName: 'Sorting Algorithms Lab',
    instructorId: 'instructor-1',
    instructorName: 'Dr. Sarah Mitchell',
    feedbackText: 'Excellent work on implementing the sorting algorithms! Your code is clean and well-documented. However, I noticed that your analysis of time complexity could be more detailed. You correctly identified Big O notation but didn\'t explain the reasoning behind each case. Also, consider adding more test cases to demonstrate edge cases.',
    rubricData: {
      implementation: { score: 45, max: 50 },
      documentation: { score: 19, max: 20 },
      analysis: { score: 22, max: 30 },
    },
    score: 86,
    pointsPossible: 100,
    sentimentScore: 0.7,
    sentimentLabel: 'positive',
    keyThemes: ['time complexity', 'documentation', 'test cases'],
    strengths: ['Clean code', 'Good documentation', 'Correct implementation'],
    improvements: ['More detailed time complexity analysis', 'Add edge case testing'],
    analyzedAt: '2024-10-28T10:00:00Z',
    aiExplanation: 'Your instructor is pleased with your implementation and code quality. The main area for improvement is providing more detailed explanations of your algorithmic analysis, particularly regarding time complexity reasoning.',
    createdAt: '2024-10-28T09:00:00Z',
  },
  {
    id: 'feedback-2',
    userId: 'mock-user-1',
    submissionId: 'submission-2',
    courseId: 'course-2',
    courseName: 'Calculus II',
    assignmentId: 'assignment-2',
    assignmentName: 'Integration Problem Set #3',
    instructorId: 'instructor-2',
    instructorName: 'Prof. James Chen',
    feedbackText: 'Good effort on the problem set. Your approach to problems 1-5 was correct, and you showed your work clearly. Problem 6 needs more attention - you made an error in the u-substitution step. Remember to always check your derivative to verify your substitution is correct. Your final answers would benefit from simplification.',
    rubricData: {
      correctness: { score: 35, max: 50 },
      process: { score: 22, max: 25 },
      presentation: { score: 18, max: 25 },
    },
    score: 75,
    pointsPossible: 100,
    sentimentScore: 0.4,
    sentimentLabel: 'neutral',
    keyThemes: ['u-substitution', 'verification', 'simplification'],
    strengths: ['Clear work shown', 'Correct approach on most problems'],
    improvements: ['Double-check u-substitution', 'Simplify final answers', 'Verify with derivatives'],
    analyzedAt: '2024-10-26T15:00:00Z',
    aiExplanation: 'The instructor appreciates your effort and clear presentation. Focus on verifying your substitution techniques and simplifying your final answers. Consider working through similar u-substitution problems for practice.',
    createdAt: '2024-10-26T14:00:00Z',
  },
  {
    id: 'feedback-3',
    userId: 'mock-user-1',
    submissionId: 'submission-3',
    courseId: 'course-3',
    courseName: 'English Literature',
    assignmentId: 'assignment-3',
    assignmentName: 'Victorian Poetry Analysis Essay',
    instructorId: 'instructor-3',
    instructorName: 'Dr. Emily Rodriguez',
    feedbackText: 'Your analysis shows a deep understanding of the Victorian era themes. I particularly enjoyed your interpretation of Tennyson\'s "In Memoriam." However, your essay needs better structure and organization. The introduction should more clearly state your thesis, and your body paragraphs would benefit from stronger topic sentences. Also, make sure to cite sources properly using MLA format. Watch for comma splices in your writing.',
    rubricData: {
      analysis: { score: 42, max: 45 },
      structure: { score: 25, max: 35 },
      citations: { score: 12, max: 20 },
    },
    score: 79,
    pointsPossible: 100,
    sentimentScore: 0.5,
    sentimentLabel: 'neutral',
    keyThemes: ['structure', 'thesis statement', 'citations', 'grammar'],
    strengths: ['Deep understanding', 'Strong analysis', 'Good interpretation'],
    improvements: ['Better essay structure', 'Clear thesis statement', 'MLA citation format', 'Grammar (comma splices)'],
    analyzedAt: '2024-10-25T11:00:00Z',
    aiExplanation: 'Your instructor values your analytical skills and understanding. The priority is improving your essay structure and citation practices. Consider outlining before writing and reviewing MLA format guidelines.',
    createdAt: '2024-10-25T10:00:00Z',
  },
  {
    id: 'feedback-4',
    userId: 'mock-user-1',
    submissionId: 'submission-4',
    courseId: 'course-4',
    courseName: 'Physics I',
    assignmentId: 'assignment-4',
    assignmentName: 'Kinematics Lab Report',
    instructorId: 'instructor-4',
    instructorName: 'Dr. Robert Kim',
    feedbackText: 'Your experimental data collection was excellent, and your measurements appear to be very accurate. The data analysis section was thorough. However, your lab report structure needs significant improvement. The introduction should provide more background on kinematics principles. Your conclusion is too brief and doesn\'t adequately discuss error sources or experimental limitations. Please follow the lab report template more closely next time.',
    rubricData: {
      data_collection: { score: 28, max: 30 },
      analysis: { score: 23, max: 25 },
      structure: { score: 15, max: 25 },
      conclusion: { score: 12, max: 20 },
    },
    score: 78,
    pointsPossible: 100,
    sentimentScore: 0.3,
    sentimentLabel: 'neutral',
    keyThemes: ['structure', 'introduction', 'conclusion', 'error analysis'],
    strengths: ['Excellent data collection', 'Accurate measurements', 'Thorough analysis'],
    improvements: ['Follow lab report template', 'Expand introduction', 'Detailed conclusion', 'Discuss error sources'],
    analyzedAt: '2024-10-23T14:00:00Z',
    aiExplanation: 'Your experimental work is strong, but the written component needs attention. Focus on following the lab report structure, providing more context in your introduction, and thoroughly discussing limitations and errors in your conclusion.',
    createdAt: '2024-10-23T13:00:00Z',
  },
  {
    id: 'feedback-5',
    userId: 'mock-user-1',
    submissionId: 'submission-5',
    courseId: 'course-1',
    courseName: 'Introduction to Computer Science',
    assignmentId: 'assignment-5',
    assignmentName: 'Binary Search Tree Project',
    instructorId: 'instructor-1',
    instructorName: 'Dr. Sarah Mitchell',
    feedbackText: 'Outstanding work on this project! Your implementation of the BST is efficient and handles edge cases well. I\'m impressed by your thorough testing suite and clear documentation. The code is well-structured and easy to follow. Minor suggestion: consider adding more inline comments in the balancing function as that logic is complex. This is one of the best submissions I\'ve received for this assignment.',
    rubricData: {
      implementation: { score: 49, max: 50 },
      testing: { score: 28, max: 30 },
      documentation: { score: 19, max: 20 },
    },
    score: 96,
    pointsPossible: 100,
    sentimentScore: 0.95,
    sentimentLabel: 'positive',
    keyThemes: ['implementation', 'testing', 'documentation'],
    strengths: ['Efficient implementation', 'Excellent edge case handling', 'Thorough testing', 'Clear documentation', 'Well-structured code'],
    improvements: ['Add inline comments to balancing function'],
    analyzedAt: '2024-10-20T16:00:00Z',
    aiExplanation: 'Excellent work! Your instructor is very impressed with your implementation, testing, and documentation. This is a model submission with only minor suggestions for improvement.',
    createdAt: '2024-10-20T15:00:00Z',
  },
  {
    id: 'feedback-6',
    userId: 'mock-user-1',
    submissionId: 'submission-6',
    courseId: 'course-3',
    courseName: 'English Literature',
    assignmentId: 'assignment-6',
    assignmentName: 'Poetry Discussion Board Post',
    instructorId: 'instructor-3',
    instructorName: 'Dr. Emily Rodriguez',
    feedbackText: 'Good engagement with the material. Your points about symbolism were insightful. For future posts, remember to structure your response more clearly with a topic sentence. Also, make sure to respond to at least two classmates\' posts as required.',
    rubricData: {
      content: { score: 18, max: 20 },
      structure: { score: 6, max: 10 },
      engagement: { score: 5, max: 10 },
    },
    score: 29,
    pointsPossible: 40,
    sentimentScore: 0.6,
    sentimentLabel: 'positive',
    keyThemes: ['structure', 'engagement', 'topic sentence'],
    strengths: ['Insightful analysis', 'Good understanding of symbolism'],
    improvements: ['Add clear topic sentence', 'Respond to classmates\' posts', 'Better structure'],
    analyzedAt: '2024-10-18T09:00:00Z',
    aiExplanation: 'Your content is strong, but remember the format requirements for discussion posts. Structure your response clearly and engage with your peers\' ideas.',
    createdAt: '2024-10-18T08:00:00Z',
  },
  {
    id: 'feedback-7',
    userId: 'mock-user-1',
    submissionId: 'submission-7',
    courseId: 'course-2',
    courseName: 'Calculus II',
    assignmentId: 'assignment-7',
    assignmentName: 'Series Convergence Quiz',
    instructorId: 'instructor-2',
    instructorName: 'Prof. James Chen',
    feedbackText: 'You showed good understanding of the ratio test and comparison test. However, you need to work on the integral test - you made errors in setting up the integral for problem 3. Also, remember to always state your conclusion clearly (converges/diverges). Your work is generally well-organized.',
    rubricData: {
      ratio_test: { score: 10, max: 10 },
      comparison_test: { score: 9, max: 10 },
      integral_test: { score: 6, max: 10 },
      presentation: { score: 8, max: 10 },
    },
    score: 33,
    pointsPossible: 40,
    sentimentScore: 0.5,
    sentimentLabel: 'neutral',
    keyThemes: ['integral test', 'conclusions', 'organization'],
    strengths: ['Good understanding of ratio test', 'Strong comparison test', 'Well-organized work'],
    improvements: ['Practice integral test setup', 'State conclusions clearly'],
    analyzedAt: '2024-10-15T13:00:00Z',
    aiExplanation: 'You have a solid grasp of several convergence tests. Focus on the integral test and practice setting up integrals correctly. Always explicitly state whether a series converges or diverges.',
    createdAt: '2024-10-15T12:00:00Z',
  },
];

// =====================================================
// MOCK FEEDBACK PATTERNS
// =====================================================

export const mockFeedbackPatterns: FeedbackPattern[] = [
  {
    id: 'pattern-1',
    userId: 'mock-user-1',
    patternType: 'weakness',
    category: 'structure',
    description: 'Instructors frequently mention that your work needs better organization and structure',
    evidence: [
      { feedback_id: 'feedback-3', mention: 'essay needs better structure and organization' },
      { feedback_id: 'feedback-4', mention: 'lab report structure needs significant improvement' },
      { feedback_id: 'feedback-6', mention: 'structure your response more clearly' },
    ],
    occurrences: 3,
    coursesAffected: ['course-3', 'course-4'],
    assignmentsAffected: ['assignment-3', 'assignment-4', 'assignment-6'],
    firstDetectedAt: '2024-10-18T08:00:00Z',
    lastDetectedAt: '2024-10-25T10:00:00Z',
    severity: 'high',
    confidence: 0.85,
    improvementTrend: 'stable',
  },
  {
    id: 'pattern-2',
    userId: 'mock-user-1',
    patternType: 'weakness',
    category: 'citations',
    description: 'Citation format and proper sourcing needs attention',
    evidence: [
      { feedback_id: 'feedback-3', mention: 'cite sources properly using MLA format' },
    ],
    occurrences: 1,
    coursesAffected: ['course-3'],
    assignmentsAffected: ['assignment-3'],
    firstDetectedAt: '2024-10-25T10:00:00Z',
    lastDetectedAt: '2024-10-25T10:00:00Z',
    severity: 'medium',
    confidence: 0.70,
    improvementTrend: 'stable',
  },
  {
    id: 'pattern-3',
    userId: 'mock-user-1',
    patternType: 'strength',
    category: 'implementation',
    description: 'Consistently praised for strong implementation and coding skills',
    evidence: [
      { feedback_id: 'feedback-1', mention: 'Excellent work on implementing the sorting algorithms' },
      { feedback_id: 'feedback-5', mention: 'implementation of the BST is efficient and handles edge cases well' },
    ],
    occurrences: 2,
    coursesAffected: ['course-1'],
    assignmentsAffected: ['assignment-1', 'assignment-5'],
    firstDetectedAt: '2024-10-20T15:00:00Z',
    lastDetectedAt: '2024-10-28T09:00:00Z',
    severity: 'low',
    confidence: 0.90,
    improvementTrend: 'improving',
  },
  {
    id: 'pattern-4',
    userId: 'mock-user-1',
    patternType: 'strength',
    category: 'analysis',
    description: 'Strong analytical and interpretive skills noted by instructors',
    evidence: [
      { feedback_id: 'feedback-1', mention: 'Your code is clean and well-documented' },
      { feedback_id: 'feedback-3', mention: 'shows a deep understanding of the Victorian era themes' },
      { feedback_id: 'feedback-4', mention: 'data analysis section was thorough' },
    ],
    occurrences: 3,
    coursesAffected: ['course-1', 'course-3', 'course-4'],
    assignmentsAffected: ['assignment-1', 'assignment-3', 'assignment-4'],
    firstDetectedAt: '2024-10-23T13:00:00Z',
    lastDetectedAt: '2024-10-28T09:00:00Z',
    severity: 'low',
    confidence: 0.88,
    improvementTrend: 'stable',
  },
  {
    id: 'pattern-5',
    userId: 'mock-user-1',
    patternType: 'weakness',
    category: 'conclusions',
    description: 'Need to provide more detailed conclusions and summaries',
    evidence: [
      { feedback_id: 'feedback-4', mention: 'Your conclusion is too brief' },
      { feedback_id: 'feedback-7', mention: 'remember to always state your conclusion clearly' },
    ],
    occurrences: 2,
    coursesAffected: ['course-2', 'course-4'],
    assignmentsAffected: ['assignment-4', 'assignment-7'],
    firstDetectedAt: '2024-10-15T12:00:00Z',
    lastDetectedAt: '2024-10-23T13:00:00Z',
    severity: 'medium',
    confidence: 0.75,
    improvementTrend: 'stable',
  },
  {
    id: 'pattern-6',
    userId: 'mock-user-1',
    patternType: 'strength',
    category: 'documentation',
    description: 'Consistently excellent documentation and clear presentation',
    evidence: [
      { feedback_id: 'feedback-1', mention: 'Your code is clean and well-documented' },
      { feedback_id: 'feedback-5', mention: 'I\'m impressed by your thorough testing suite and clear documentation' },
      { feedback_id: 'feedback-7', mention: 'Your work is generally well-organized' },
    ],
    occurrences: 3,
    coursesAffected: ['course-1', 'course-2'],
    assignmentsAffected: ['assignment-1', 'assignment-5', 'assignment-7'],
    firstDetectedAt: '2024-10-15T12:00:00Z',
    lastDetectedAt: '2024-10-28T09:00:00Z',
    severity: 'low',
    confidence: 0.92,
    improvementTrend: 'stable',
  },
];

// =====================================================
// MOCK IMPROVEMENT GOALS
// =====================================================

export const mockImprovementGoals: ImprovementGoal[] = [
  {
    id: 'goal-1',
    userId: 'mock-user-1',
    patternId: 'pattern-1',
    goalTitle: 'Improve Essay and Report Structure',
    goalDescription: 'Develop stronger organizational skills for written assignments by following templates, using clear topic sentences, and creating detailed outlines before writing.',
    goalCategory: 'Writing Skills',
    actionItems: [
      {
        step: 'Review assignment templates and rubrics before starting',
        how: 'Read the provided template or rubric carefully and create a checklist of required sections',
        resources: ['Course syllabus', 'Assignment instructions'],
        completed: false,
      },
      {
        step: 'Create a detailed outline before writing',
        how: 'Spend 15-20 minutes outlining main points, topic sentences, and supporting evidence',
        resources: ['Writing center outline guide'],
        completed: false,
      },
      {
        step: 'Use strong topic sentences for each paragraph',
        how: 'Start each paragraph with a clear sentence that states the main idea',
        resources: ['Purdue OWL topic sentence guide'],
        completed: false,
      },
      {
        step: 'Review and revise for structure',
        how: 'Before submitting, check that each section follows the template and flows logically',
        resources: [],
        completed: false,
      },
    ],
    resources: [
      {
        title: 'Purdue OWL - Essay Structure',
        type: 'article',
        url: 'https://owl.purdue.edu/owl/general_writing/academic_writing/essay_writing/index.html',
        description: 'Comprehensive guide to essay organization and structure',
      },
      {
        title: 'Lab Report Template',
        type: 'tool',
        description: 'Standard scientific lab report template with all required sections',
      },
      {
        title: 'Writing Center Office Hours',
        type: 'practice',
        description: 'Get one-on-one help with outlining and structuring your assignments',
      },
    ],
    successCriteria: [
      'Receive positive feedback on structure from instructors',
      'Follow templates for all written assignments',
      'Create outlines before writing for 5 consecutive assignments',
    ],
    targetCourses: ['course-3', 'course-4'],
    targetTimeline: '4 weeks',
    status: 'in_progress',
    progress: 25,
    progressNotes: ['Started reviewing templates before assignments'],
    createdAt: '2024-10-26T10:00:00Z',
    startedAt: '2024-10-26T10:00:00Z',
  },
  {
    id: 'goal-2',
    userId: 'mock-user-1',
    patternId: 'pattern-2',
    goalTitle: 'Master MLA Citation Format',
    goalDescription: 'Learn and consistently apply proper MLA citation format for all sources in English Literature assignments.',
    goalCategory: 'Academic Writing',
    actionItems: [
      {
        step: 'Study MLA 9th edition guidelines',
        how: 'Review the official MLA Handbook sections on in-text citations and works cited',
        resources: ['MLA Handbook 9th ed.', 'Purdue OWL MLA Guide'],
        completed: true,
      },
      {
        step: 'Practice with citation examples',
        how: 'Complete 10 practice citations covering different source types (books, articles, websites)',
        resources: ['MLA practice worksheets'],
        completed: false,
      },
      {
        step: 'Use citation management tool',
        how: 'Set up Zotero or EasyBib to help format citations correctly',
        resources: ['Zotero tutorial', 'EasyBib'],
        completed: false,
      },
      {
        step: 'Have writing center review citations',
        how: 'Before submitting papers, have writing center verify your citations are correct',
        resources: ['Writing Center appointments'],
        completed: false,
      },
    ],
    resources: [
      {
        title: 'Purdue OWL - MLA Formatting and Style Guide',
        type: 'article',
        url: 'https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_formatting_and_style_guide.html',
        description: 'Complete MLA citation guide with examples',
      },
      {
        title: 'Zotero Citation Manager',
        type: 'tool',
        url: 'https://www.zotero.org/',
        description: 'Free tool to manage references and create citations',
      },
    ],
    successCriteria: [
      'Zero citation errors on next 3 English Literature papers',
      'Complete citation practice worksheet with 90%+ accuracy',
    ],
    targetCourses: ['course-3'],
    targetTimeline: '3 weeks',
    status: 'in_progress',
    progress: 40,
    progressNotes: ['Studied MLA guidelines', 'Started practice exercises'],
    createdAt: '2024-10-25T14:00:00Z',
    startedAt: '2024-10-25T14:00:00Z',
  },
  {
    id: 'goal-3',
    userId: 'mock-user-1',
    patternId: 'pattern-5',
    goalTitle: 'Write Stronger Conclusions',
    goalDescription: 'Develop the ability to write comprehensive, detailed conclusions that summarize findings, discuss limitations, and state results clearly.',
    goalCategory: 'Scientific Writing',
    actionItems: [
      {
        step: 'Study effective conclusion examples',
        how: 'Review sample lab reports and papers with strong conclusion sections',
        resources: ['Course examples', 'Lab manual'],
        completed: false,
      },
      {
        step: 'Create conclusion checklist',
        how: 'Make a checklist: summarize results, discuss errors, state limitations, suggest improvements',
        resources: [],
        completed: false,
      },
      {
        step: 'Allocate more time for conclusions',
        how: 'Spend at least 20-30 minutes writing and revising the conclusion section',
        resources: [],
        completed: false,
      },
      {
        step: 'Explicitly state final answers',
        how: 'Always include clear statements like "The series converges" or "The hypothesis is supported"',
        resources: [],
        completed: false,
      },
    ],
    resources: [
      {
        title: 'How to Write a Lab Report Conclusion',
        type: 'article',
        description: 'Guide specifically for scientific conclusion sections',
      },
    ],
    successCriteria: [
      'Positive feedback on conclusion sections in next 3 assignments',
      'No comments about brevity or missing elements in conclusions',
    ],
    targetCourses: ['course-2', 'course-4'],
    targetTimeline: '3 weeks',
    status: 'active',
    progress: 10,
    progressNotes: [],
    createdAt: '2024-10-24T09:00:00Z',
  },
];

// =====================================================
// MOCK SENTIMENT STATS
// =====================================================

export const mockSentimentStats: SentimentStats = {
  positive: 3,
  neutral: 4,
  negative: 0,
  total: 7,
  average: 0.59,
  positivePercentage: 42.86,
  neutralPercentage: 57.14,
  negativePercentage: 0,
};

// =====================================================
// MOCK TIMELINE
// =====================================================

export const mockTimelineEntries: TimelineEntry[] = [
  {
    id: 'timeline-1',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Sorting Algorithms Lab',
    eventDescription: 'Excellent implementation with suggestions for analysis improvement',
    courseId: 'course-1',
    courseName: 'Introduction to Computer Science',
    assignmentId: 'assignment-1',
    assignmentName: 'Sorting Algorithms Lab',
    sentimentLabel: 'positive',
    score: 86,
    pointsPossible: 100,
    eventDate: '2024-10-28T09:00:00Z',
  },
  {
    id: 'timeline-2',
    eventType: 'goal_created',
    eventTitle: 'Created improvement goal: Improve Essay Structure',
    eventDescription: 'Based on recurring feedback pattern about organization',
    eventDate: '2024-10-26T10:00:00Z',
  },
  {
    id: 'timeline-3',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Integration Problem Set',
    eventDescription: 'Good effort with areas for improvement in u-substitution',
    courseId: 'course-2',
    courseName: 'Calculus II',
    assignmentId: 'assignment-2',
    assignmentName: 'Integration Problem Set #3',
    sentimentLabel: 'neutral',
    score: 75,
    pointsPossible: 100,
    eventDate: '2024-10-26T14:00:00Z',
  },
  {
    id: 'timeline-4',
    eventType: 'goal_created',
    eventTitle: 'Created improvement goal: Master MLA Citations',
    eventDescription: 'To address citation format issues in literature assignments',
    eventDate: '2024-10-25T14:00:00Z',
  },
  {
    id: 'timeline-5',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Victorian Poetry Essay',
    eventDescription: 'Strong analysis but needs better structure and citations',
    courseId: 'course-3',
    courseName: 'English Literature',
    assignmentId: 'assignment-3',
    assignmentName: 'Victorian Poetry Analysis Essay',
    sentimentLabel: 'neutral',
    score: 79,
    pointsPossible: 100,
    eventDate: '2024-10-25T10:00:00Z',
  },
  {
    id: 'timeline-6',
    eventType: 'pattern_detected',
    eventTitle: 'Pattern detected: Structure needs improvement',
    eventDescription: 'Multiple instructors mentioning organization issues',
    eventDate: '2024-10-25T10:30:00Z',
  },
  {
    id: 'timeline-7',
    eventType: 'goal_created',
    eventTitle: 'Created improvement goal: Write Stronger Conclusions',
    eventDescription: 'Based on feedback about brief or incomplete conclusions',
    eventDate: '2024-10-24T09:00:00Z',
  },
  {
    id: 'timeline-8',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Kinematics Lab Report',
    eventDescription: 'Excellent data collection but structure needs work',
    courseId: 'course-4',
    courseName: 'Physics I',
    assignmentId: 'assignment-4',
    assignmentName: 'Kinematics Lab Report',
    sentimentLabel: 'neutral',
    score: 78,
    pointsPossible: 100,
    eventDate: '2024-10-23T13:00:00Z',
  },
  {
    id: 'timeline-9',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Binary Search Tree Project',
    eventDescription: 'Outstanding work - one of the best submissions!',
    courseId: 'course-1',
    courseName: 'Introduction to Computer Science',
    assignmentId: 'assignment-5',
    assignmentName: 'Binary Search Tree Project',
    sentimentLabel: 'positive',
    score: 96,
    pointsPossible: 100,
    eventDate: '2024-10-20T15:00:00Z',
  },
  {
    id: 'timeline-10',
    eventType: 'pattern_detected',
    eventTitle: 'Strength pattern: Strong implementation skills',
    eventDescription: 'Consistently praised for coding implementation',
    eventDate: '2024-10-20T16:00:00Z',
  },
  {
    id: 'timeline-11',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Poetry Discussion Post',
    eventDescription: 'Insightful content, remember to engage with classmates',
    courseId: 'course-3',
    courseName: 'English Literature',
    assignmentId: 'assignment-6',
    assignmentName: 'Poetry Discussion Board Post',
    sentimentLabel: 'positive',
    score: 29,
    pointsPossible: 40,
    eventDate: '2024-10-18T08:00:00Z',
  },
  {
    id: 'timeline-12',
    eventType: 'feedback_received',
    eventTitle: 'Received feedback on Series Convergence Quiz',
    eventDescription: 'Good understanding of most tests, practice integral test',
    courseId: 'course-2',
    courseName: 'Calculus II',
    assignmentId: 'assignment-7',
    assignmentName: 'Series Convergence Quiz',
    sentimentLabel: 'neutral',
    score: 33,
    pointsPossible: 40,
    eventDate: '2024-10-15T12:00:00Z',
  },
];

// =====================================================
// MOCK TRENDS
// =====================================================

export const mockFeedbackTrends: FeedbackTrend[] = [
  {
    periodLabel: 'Week 1',
    periodStart: '2024-10-14T00:00:00Z',
    averageSentiment: 0.55,
    averageScorePercentage: 82.5,
    feedbackCount: 2,
  },
  {
    periodLabel: 'Week 2',
    periodStart: '2024-10-21T00:00:00Z',
    averageSentiment: 0.78,
    averageScorePercentage: 87.5,
    feedbackCount: 3,
  },
  {
    periodLabel: 'Week 3',
    periodStart: '2024-10-28T00:00:00Z',
    averageSentiment: 0.46,
    averageScorePercentage: 80.0,
    feedbackCount: 2,
  },
];

// =====================================================
// EXPORT ALL MOCK DATA
// =====================================================

export function getMockFeedbackData() {
  return {
    feedback: mockInstructorFeedback,
    patterns: mockFeedbackPatterns,
    goals: mockImprovementGoals,
    sentimentStats: mockSentimentStats,
    timeline: mockTimelineEntries,
    trends: mockFeedbackTrends,
  };
}
