/**
 * Mock Canvas LMS Data
 *
 * Comprehensive mock data for Canvas API responses
 * Used when VITE_USE_CANVAS_MOCK=true
 *
 * This allows the app to function without a real Canvas connection
 */

import type {
  CanvasCourse,
  CanvasAssignment,
  CanvasSubmission,
  CanvasCalendarEvent,
  CanvasModule,
  CanvasModuleItem,
  CanvasEnrollment,
} from '../types/canvas';

// ============================================================================
// MOCK COURSES
// ============================================================================

export const mockCanvasCourses: CanvasCourse[] = [
  {
    id: 101,
    uuid: 'uuid-101',
    name: 'Introduction to Psychology',
    course_code: 'PSYCH 101',
    workflow_state: 'available',
    account_id: 1,
    root_account_id: 1,
    enrollment_term_id: 1,
    created_at: '2024-01-01T00:00:00Z',
    start_at: '2024-09-01T00:00:00Z',
    end_at: '2024-12-15T23:59:59Z',
    enrollments: [
      {
        id: 1,
        type: 'TeacherEnrollment',
        role: 'TeacherEnrollment',
        user_id: 1001,
        course_id: 101,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        course_section_id: 1,
        root_account_id: 1,
        limit_privileges_to_course_section: false,
        enrollment_state: 'active',
        role_id: 1,
        html_url: 'https://canvas.example.com/courses/101/users/1001',
      } as CanvasEnrollment,
    ],
    total_students: 28,
    calendar: {
      ics: 'https://canvas.example.com/feeds/calendars/course_1.ics',
    },
  },
  {
    id: 102,
    uuid: 'uuid-102',
    name: 'English Literature',
    course_code: 'ENG 201',
    workflow_state: 'available',
    account_id: 1,
    root_account_id: 1,
    enrollment_term_id: 1,
    created_at: '2024-01-01T00:00:00Z',
    start_at: '2024-09-01T00:00:00Z',
    end_at: '2024-12-15T23:59:59Z',
    enrollments: [
      {
        id: 2,
        type: 'TeacherEnrollment',
        role: 'TeacherEnrollment',
        user_id: 1001,
        course_id: 102,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        course_section_id: 2,
        root_account_id: 1,
        limit_privileges_to_course_section: false,
        enrollment_state: 'active',
        role_id: 1,
        html_url: 'https://canvas.example.com/courses/102/users/1001',
      } as CanvasEnrollment,
    ],
    total_students: 24,
    calendar: {
      ics: 'https://canvas.example.com/feeds/calendars/course_2.ics',
    },
  },
  {
    id: 103,
    uuid: 'uuid-103',
    name: 'World History',
    course_code: 'HIST 101',
    workflow_state: 'available',
    account_id: 1,
    root_account_id: 1,
    enrollment_term_id: 1,
    created_at: '2024-01-01T00:00:00Z',
    start_at: '2024-09-01T00:00:00Z',
    end_at: '2024-12-15T23:59:59Z',
    enrollments: [
      {
        id: 3,
        type: 'TeacherEnrollment',
        role: 'TeacherEnrollment',
        user_id: 1001,
        course_id: 103,
        created_at: '2024-01-01T00:00:00Z',
        updated_at: '2024-01-01T00:00:00Z',
        course_section_id: 3,
        root_account_id: 1,
        limit_privileges_to_course_section: false,
        enrollment_state: 'active',
        role_id: 1,
        html_url: 'https://canvas.example.com/courses/103/users/1001',
      } as CanvasEnrollment,
    ],
    total_students: 30,
    calendar: {
      ics: 'https://canvas.example.com/feeds/calendars/course_3.ics',
    },
  },
];

// ============================================================================
// MOCK ASSIGNMENTS
// ============================================================================

export const mockCanvasAssignments: CanvasAssignment[] = [
  // Psychology Course Assignments
  {
    id: 201,
    name: 'Chapter 1 Quiz',
    description: 'Quiz covering introduction to psychology',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-09-15T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 101,
    html_url: 'https://canvas.example.com/courses/101/assignments/201',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 1,
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_quiz'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  {
    id: 202,
    name: 'Research Paper: Cognitive Psychology',
    description: 'Write a 5-page research paper on cognitive psychology topics',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-10-01T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 101,
    html_url: 'https://canvas.example.com/courses/101/assignments/202',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 2,
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  {
    id: 203,
    name: 'Midterm Exam',
    description: 'Comprehensive exam covering chapters 1-5',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-10-20T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 101,
    html_url: 'https://canvas.example.com/courses/101/assignments/203',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 3,
    points_possible: 200,
    grading_type: 'points',
    submission_types: ['online_quiz'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  {
    id: 204,
    name: 'Weekly Discussion: Social Psychology',
    description: 'Participate in the discussion on social psychology concepts',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-11-01T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 101,
    html_url: 'https://canvas.example.com/courses/101/assignments/204',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 4,
    points_possible: 50,
    grading_type: 'points',
    submission_types: ['discussion_topic'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  // English Literature Assignments
  {
    id: 205,
    name: 'Shakespeare Essay',
    description: 'Analyze a Shakespeare play of your choice',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-09-25T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 102,
    html_url: 'https://canvas.example.com/courses/102/assignments/205',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 1,
    points_possible: 100,
    grading_type: 'points',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  {
    id: 206,
    name: 'Poetry Analysis',
    description: 'Analyze and discuss selected poems',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-10-10T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 102,
    html_url: 'https://canvas.example.com/courses/102/assignments/206',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 2,
    points_possible: 75,
    grading_type: 'points',
    submission_types: ['online_text_entry'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  // History Assignments
  {
    id: 207,
    name: 'Ancient Civilizations Project',
    description: 'Research project on ancient civilizations',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-09-30T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 103,
    html_url: 'https://canvas.example.com/courses/103/assignments/207',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 1,
    points_possible: 150,
    grading_type: 'points',
    submission_types: ['online_upload'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
  {
    id: 208,
    name: 'Weekly Quiz: World War II',
    description: 'Quiz on WWII events and significance',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    due_at: '2024-10-05T23:59:59Z',
    lock_at: null,
    unlock_at: null,
    has_overrides: false,
    course_id: 103,
    html_url: 'https://canvas.example.com/courses/103/assignments/208',
    assignment_group_id: 1,
    due_date_required: false,
    max_name_length: 255,
    peer_reviews: false,
    automatic_peer_reviews: false,
    position: 2,
    points_possible: 50,
    grading_type: 'points',
    submission_types: ['online_quiz'],
    has_submitted_submissions: false,
    published: true,
    unpublishable: false,
    only_visible_to_overrides: false,
    locked_for_user: false,
    workflow_state: 'published',
  } as CanvasAssignment,
];

// ============================================================================
// MOCK SUBMISSIONS
// ============================================================================

export const mockCanvasSubmissions: CanvasSubmission[] = [
  // Student submissions for various assignments
  {
    id: 301,
    assignment_id: 201,
    user_id: 2001,
    workflow_state: 'graded',
    score: 85,
    grade: '85',
    submitted_at: '2024-09-14T18:30:00Z',
    graded_at: '2024-09-16T10:00:00Z',
    late: false,
    missing: false,
    excused: false,
    grade_matches_current_submission: true,
    attempt: 1,
    preview_url: 'https://canvas.example.com/courses/101/assignments/201/submissions/2001?preview=1',
  },
  {
    id: 302,
    assignment_id: 201,
    user_id: 2002,
    workflow_state: 'graded',
    score: 92,
    grade: '92',
    submitted_at: '2024-09-15T12:00:00Z',
    graded_at: '2024-09-16T10:15:00Z',
    late: false,
    missing: false,
    excused: false,
    grade_matches_current_submission: true,
    attempt: 1,
    preview_url: 'https://canvas.example.com/courses/101/assignments/201/submissions/2002?preview=1',
  },
  {
    id: 303,
    assignment_id: 201,
    user_id: 2003,
    workflow_state: 'submitted',
    submitted_at: '2024-09-16T22:00:00Z',
    late: true,
    missing: false,
    excused: false,
    grade_matches_current_submission: true,
    attempt: 1,
    preview_url: 'https://canvas.example.com/courses/101/assignments/201/submissions/2003?preview=1',
  },
  {
    id: 304,
    assignment_id: 202,
    user_id: 2001,
    workflow_state: 'graded',
    score: 78,
    grade: '78',
    submitted_at: '2024-10-01T20:00:00Z',
    graded_at: '2024-10-03T14:00:00Z',
    late: false,
    missing: false,
    excused: false,
    grade_matches_current_submission: true,
    attempt: 1,
    preview_url: 'https://canvas.example.com/courses/101/assignments/202/submissions/2001?preview=1',
  },
  {
    id: 305,
    assignment_id: 202,
    user_id: 2002,
    workflow_state: 'graded',
    score: 95,
    grade: '95',
    submitted_at: '2024-09-30T16:00:00Z',
    graded_at: '2024-10-03T14:30:00Z',
    late: false,
    missing: false,
    excused: false,
    grade_matches_current_submission: true,
    attempt: 1,
    preview_url: 'https://canvas.example.com/courses/101/assignments/202/submissions/2002?preview=1',
  },
];

// ============================================================================
// MOCK CALENDAR EVENTS
// ============================================================================

export const mockCanvasCalendarEvents: CanvasCalendarEvent[] = [
  {
    id: 401,
    title: 'Psychology Lecture: Introduction',
    start_at: '2024-09-05T09:00:00Z',
    end_at: '2024-09-05T10:30:00Z',
    description: 'First lecture covering course syllabus and introduction to psychology',
    location_name: 'Room 101',
    workflow_state: 'active',
    context_code: 'course_101',
    hidden: false,
    url: 'https://canvas.example.com/api/v1/calendar_events/401',
    html_url: 'https://canvas.example.com/calendar?event_id=401',
    all_day: false,
    all_day_date: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 402,
    title: 'English Literature: Shakespeare Discussion',
    start_at: '2024-09-10T14:00:00Z',
    end_at: '2024-09-10T15:30:00Z',
    description: 'In-depth discussion of Hamlet',
    location_name: 'Room 205',
    workflow_state: 'active',
    context_code: 'course_102',
    hidden: false,
    url: 'https://canvas.example.com/api/v1/calendar_events/402',
    html_url: 'https://canvas.example.com/calendar?event_id=402',
    all_day: false,
    all_day_date: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 403,
    title: 'History Exam Review Session',
    start_at: '2024-10-04T16:00:00Z',
    end_at: '2024-10-04T18:00:00Z',
    description: 'Review session for upcoming exam',
    location_name: 'Room 303',
    workflow_state: 'active',
    context_code: 'course_103',
    hidden: false,
    url: 'https://canvas.example.com/api/v1/calendar_events/403',
    html_url: 'https://canvas.example.com/calendar?event_id=403',
    all_day: false,
    all_day_date: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];

// ============================================================================
// MOCK MODULES
// ============================================================================

export const mockCanvasModules: CanvasModule[] = [
  {
    id: 501,
    name: 'Introduction to Psychology',
    position: 1,
    workflow_state: 'active',
    items_count: 5,
    items_url: '/api/v1/courses/101/modules/501/items',
    require_sequential_progress: false,
    prerequisite_module_ids: [],
    publish_final_grade: false,
  },
  {
    id: 502,
    name: 'Cognitive Psychology',
    position: 2,
    workflow_state: 'active',
    items_count: 7,
    items_url: '/api/v1/courses/101/modules/502/items',
    require_sequential_progress: false,
    prerequisite_module_ids: [],
    publish_final_grade: false,
  },
  {
    id: 503,
    name: 'Shakespeare & Drama',
    position: 1,
    workflow_state: 'active',
    items_count: 6,
    items_url: '/api/v1/courses/102/modules/503/items',
    require_sequential_progress: false,
    prerequisite_module_ids: [],
    publish_final_grade: false,
  },
];

// ============================================================================
// MOCK MODULE ITEMS
// ============================================================================

export const mockCanvasModuleItems: CanvasModuleItem[] = [
  {
    id: 601,
    module_id: 501,
    position: 1,
    title: 'Course Syllabus',
    type: 'File',
    content_id: 701,
    html_url: '/courses/101/files/701',
    url: '/api/v1/courses/101/files/701',
    indent: 0,
    new_tab: false,
    published: true,
  },
  {
    id: 602,
    module_id: 501,
    position: 2,
    title: 'Introduction Lecture Slides',
    type: 'File',
    content_id: 702,
    html_url: '/courses/101/files/702',
    url: '/api/v1/courses/101/files/702',
    indent: 0,
    new_tab: false,
    published: true,
  },
  {
    id: 603,
    module_id: 501,
    position: 3,
    title: 'Chapter 1 Reading',
    type: 'Page',
    content_id: 703,
    html_url: '/courses/101/pages/703',
    url: '/api/v1/courses/101/pages/703',
    indent: 0,
    new_tab: false,
    published: true,
  },
];

// ============================================================================
// MOCK STUDENT SUMMARIES (for analytics)
// ============================================================================

export const mockCanvasStudentSummaries = [
  {
    id: 'student-1',
    name: 'Alex Johnson',
    sortable_name: 'Johnson, Alex',
    short_name: 'Alex',
    page_views: 45,
    participations: 12,
    max_page_views: 100,
    max_participations: 20,
  },
  {
    id: 'student-2',
    name: 'Sarah Martinez',
    sortable_name: 'Martinez, Sarah',
    short_name: 'Sarah',
    page_views: 82,
    participations: 18,
    max_page_views: 100,
    max_participations: 20,
  },
  {
    id: 'student-3',
    name: 'Michael Chen',
    sortable_name: 'Chen, Michael',
    short_name: 'Michael',
    page_views: 23,
    participations: 5,
    max_page_views: 100,
    max_participations: 20,
  },
];
