name: Check Notifications

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allows manual triggering from Actions tab

jobs:
  check-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Notification Check
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            https://varogchclygvkuzfgxhh.supabase.co/functions/v1/check-notifications \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json")

          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "Response: $body"
          echo "HTTP Code: $http_code"

          if [ "$http_code" -ne 200 ]; then
            echo "Error: Notification check failed with status $http_code"
            exit 1
          fi

      - name: Parse Results
        run: |
          echo "✅ Notification check completed successfully"
          echo "Check the Supabase Edge Function logs for details"
